Add FREVersion.pm.in with deploy for FREVersion
Added the FREVersion.pm.in file that will be used to create the FREversion.pm file to share a single version across FRE.

diff --git a/t/FRE_tests/run_tests b/t/FRE_tests/run_tests
--- a/t/FRE_tests/run_tests
+++ b/t/FRE_tests/run_tests
@@ -167,7 +167,7 @@ do_deploy () {
       git fetch origin
       if [[ $? -ne 0 ]]
       then
-        echo "Error whil attempting to fetch from origin in \"${freCommands_dir}\"."
+        echo "Error while attempting to fetch from origin in \"${freCommands_dir}\"."
         echo "Failing"
         myReturn=1
       else
@@ -188,6 +188,19 @@ do_deploy () {
           echo "Reverting . . ."
           revert_repo ${freCommands_dir} ${oldCommitHash}
           myReturn=1
+        else
+          # All passed, create the FREVersion.pm module
+          versionTag=$(git describe --tags)
+          if [[ $? -eq 0 ]]
+          then
+            sed -e "s/@@FRE_VERSION_STRING@@/${versionTag}/" lib/FREVersion.pm.in > lib/FREVersion.pm
+            if [[ $? -ne 0 ]]
+            then
+              echo "Unable to create FREVersion.pm file.  Sed failed."
+            fi
+          else
+            echo "Unable to get git version information"
+          fi 
         fi
       fi
     fi
