Default to some flags instead of dying when combine string not found by combinehist

diff --git a/site/gfdl/bin/combinehist b/site/gfdl/bin/combinehist
--- a/site/gfdl/bin/combinehist
+++ b/site/gfdl/bin/combinehist
@@ -2,14 +2,6 @@
 #combine history files
 #modified from output staging script
 
-    # Get the mppnccombineOptString from the environment
-    if ( $?mppnccombineOptString ) then
-      set -r mppnccombineOptString = "$mppnccombineOptString"
-    else
-      echo "ERROR: Passing mppnccombineOptString from frepp failed"
-      exit 1
-    endif
-
     set patternGrepTail = '\.[0-9]{4,}$'
     set patternGrepRestart = '\<res\>|\<nc\>'
     set patternGrepHistory = '\<nc\>'
@@ -30,6 +22,15 @@
     if ( ! -f `which is-compressed` ) then
       echo "ERROR: The utility 'is-compressed' not found"
       exit 1
+    endif
+
+    # Get the mppnccombineOptString from the environment
+    if ( $?mppnccombineOptString ) then
+      set -r mppnccombineOptString = "$mppnccombineOptString"
+    else
+      set -r mppnccombineOptsDefault = '-64 -h 16384 -m'
+      echo "WARNING: Passing mppnccombineOptString from frepp failed, defaulting to '$mppnccombineOptsDefault'"
+      set -r mppnccombineOptString = "$mppnccombineOptsDefault"
     endif
 
     alias mppnccombine `which mppnccombine` $mppnccombineOptString
